### ISSUE TITLE
Platformio links older commits due to version number

### ISSUE THREAD

**Issue by VToegel** [adafruit/Adafruit_INA260#4] opened 2019-07-28 21:53 UTC
Dear adafruit team,

1.3.0 from (platformio) PIO’s eyes is commit 7f5760fcff3d386e0f292a289d8889f17c194903, aka 3 commits behind master.

Therefore please increase library version number to 1.3.1 to solve this issue.

Rgds Vinc

**Comment by ladyada** [comment] 2019-07-28 22:03
Hiya we didnt tag the release 1.3.0 till later
https://github.com/adafruit/Adafruit_INA260/releases
and now there are no new commits since....
@ivankravets do you know why this would be happening? can you use github release tags to indicate the version?

**Comment by ivankravets** [comment] 2019-08-11 13:18
We use tags if they are available. It seems that the tag was added later. I've just re-indexed this library and it should use the source code from https://github.com/adafruit/Adafruit_INA260/releases/tag/1.3.0

@VToegel please re-test.

**Comment by VToegel** [comment] 2019-08-11 18:24
Hi Ivan,

just deleted the lib, reinstalled, recompiled and got the same error. See picture, the casts included in the github vesion are still missing.

![Screenshot (227)](https://user-images.githubusercontent.com/27338698/62837955-05253c80-bc76-11e9-9a85-30b0041b749c.png)

**Comment by ivankravets** [comment] 2019-08-11 21:32
Could you provide a simple project to reproduce this issue? We use this code for 1.3.0 branch => https://github.com/adafruit/Adafruit_INA260/tree/1.3.0?files=1

**Comment by VToegel** [comment] 2019-08-11 22:37
I added you to the repo with the issue, where I took the screenshot from. Be reminded: it compiles now because I added the casts to the ina260 library manually...

**Comment by VToegel** [comment] 2019-08-11 22:49
🤔 Ups, just saw that the ina260 library is missing in the project, since it’s installed in the global storage. I’ll install it in the project tomorrow and upload. Without overwriting manually..

**Comment by VToegel** [comment] 2019-08-12 08:54
Hi Ivan,
i loaded all libraries to the local project and committed to the github project. I invited you to the repo, you can now clone that actual project for testing.
rgds Vinc

**Comment by ivankravets** [comment] 2019-08-12 10:38
I can't reproduce this issue. You use a very old version of a library. We recommend declaring all project dependencies in `platformio.ini`. See `lib_deps` in http://docs.platformio.org/en/latest/librarymanager/quickstart.html

Also, please remove `.pio` folder from repository. This is a temporary folder.

**Comment by VToegel** [comment] 2019-08-12 11:35
Thank you Ivan, i added the library manually, removed pio and added lib-deps.
Rgds Vinc

**Comment by ivankravets** [comment] 2019-08-12 11:45
Yes, please declare all dependencies via `lib_deps`. For example,

```
[env:myenv]
board = ...
platform = ...
lib_deps = 
    Adafruit INA260 Library@^1.3.0
    OtherDependecies...
```

**Comment by VToegel** [comment] 2019-08-12 17:32
Hi Ivan,
just for your info: i deleted all libraries, i even searched for the ina260 lib on my laptop and deleted all references. Thereafter i updated the lib deps and performed a platformio lib install:

![Screenshot (231)](https://user-images.githubusercontent.com/27338698/62884416-c1463c00-bd36-11e9-994a-9e4d81cc0d5f.png)

Since that did not work i used the library ID and then the lib showed as already installed:

![Screenshot (232)](https://user-images.githubusercontent.com/27338698/62884507-07030480-bd37-11e9-8d9f-8c7172176f9f.png)

I the compiled and then got the usual errors, since platformio again installed an old library version:

![Screenshot (233)](https://user-images.githubusercontent.com/27338698/62884541-1eda8880-bd37-11e9-936b-c67e6b3d5b7d.png)

I updated the libraries again, Platformio showed still 1.3.0 installed and up to date:

![Screenshot (234)](https://user-images.githubusercontent.com/27338698/62884582-374aa300-bd37-11e9-8ea7-7708f5a9fa91.png)

Another compilation showed the same errors:

![Screenshot (235)](https://user-images.githubusercontent.com/27338698/62884627-521d1780-bd37-11e9-98bb-8f7fd4c83fc5.png)

I finally deleted the code in the platformio lib deps folder, downloaded and copy pasted the library from github manually and all is ok.

I really dont know what happens here, maybe the screenshots help. 

Rgds Vinc

**Comment by ivankravets** [comment] 2019-08-15 10:49
Are you sure that changes which you need are in 1.3.0 release? Please download https://github.com/adafruit/Adafruit_INA260/archive/1.3.0.zip. Is it ok?

**Comment by VToegel** [comment] 2019-08-15 12:51
yes, I am sure. I downloaded this library and it works directly from GitHub. Installed via library manager of Platformio some type casts are missing..

**Comment by ivankravets** [comment] 2019-08-15 14:11
Please scroll down here https://platformio.org/lib/show/6239/Adafruit%20INA260%20Library/installation and use green Download button. Is this archive OK?

**Comment by VToegel** [comment] 2019-08-15 14:57
Yes, that archive is ok and includes the type casts.

**Comment by ivankravets** [comment] 2019-08-15 15:08
PlatformIO uses this archive when installing a library. It seems that I know where an issue is hidden. Could you try to unisntall this library from a project or remove `.pio` folder manually. Then open PlatformIO IDE Terminal and type `pio update` or use PIO Home > LIbraries > Updates.
Now, try to build project, PlatformIO will install all dependencies automatically. Does it work now?

**Comment by VToegel** [comment] 2019-08-15 15:15
unfortunately, no:

![Screenshot (240)](https://user-images.githubusercontent.com/27338698/63105039-4d976f80-bf80-11e9-8156-5da95e5bea4a.png)
![Screenshot (241)](https://user-images.githubusercontent.com/27338698/63105040-4e300600-bf80-11e9-97f6-cd679db1fbf0.png)
![Screenshot (243)](https://user-images.githubusercontent.com/27338698/63105041-4e300600-bf80-11e9-9b10-ada0d49bad26.png)
![Screenshot (244)](https://user-images.githubusercontent.com/27338698/63105042-4e300600-bf80-11e9-8c43-a02d4b93eee8.png)

**Comment by ladyada** [comment] 2019-08-20 17:18
hiya im gonna close this issue cause it seems like its a pio thing - we can  bump a new release if ya want, just let us know :)

**Closed as completed by ladyada** 2019-08-20 17:18 UTC
